Shooter mode WIP
WilKen3/RobotCodeTest1 pull request #12
Opened 2022-02-18 09:43 UTC by WilKen3

2022-02-20 04:19 UTC, Hirose-Yuto requested changes
readSensorsで色々センサー類の値は読み出しておいて欲しいかな
アームの角度とか、シューターの速度とか。
使い道は今の所なくても役立つ可能性はあるから

あと、PIDのゲインを簡潔に書くやり方あるのでそれもやろう（後程伝えます）

2022-02-20 04:19 UTC, Hirose-Yuto commented on src/main/java/frc/robot/mode/ShooterMode.java
> +        }
細かいけど、elseでこれを書く必要はないかな
モードを維持することよりも、変えることのほうに焦点を置いているから

2022-02-20 04:19 UTC, Hirose-Yuto commented on src/main/java/frc/robot/mode/ShooterMode.java
> +        if(Math.abs(State.forSpeed) > 0 || Math.abs(State.sideSpeed) > 0){
forSpeed, sideSpeedをshooterMode中変えてないから全く制御できなくなっちゃうね

2022-02-20 04:19 UTC, Hirose-Yuto commented on src/main/java/frc/robot/component/Drive.java
> +        Ddrive.arcadeDrive(Const.neutral,Const.neutral);
neutralってすることで0を冗長でも、マジックナンバーでも無くしてるのはいいね

2022-02-20 04:19 UTC, Hirose-Yuto commented on src/main/java/frc/robot/component/Arm.java
> +    if(getArmAngle() == -32) {
マジックナンバーなのはちょっとアレだね
最高角度と最低角度はConstで定義してるからそれ使おう

2022-02-20 04:19 UTC, Hirose-Yuto commented on src/main/java/frc/robot/component/Arm.java
> +        ArmPercentOutputUp(State.lTrigger);
lTriggerだと何の数字なのか分かりにくいから、もう少しいい名前をつけよう
armPercentOutputとかでもいいから

2022-02-20 04:19 UTC, Hirose-Yuto commented on src/main/java/frc/robot/State.java
> +    }
これ使ってないからまあ消してもいいね

2022-02-20 04:34 UTC, WilKen3 commented on src/main/java/frc/robot/State.java
> +    }
☑

2022-02-20 04:34 UTC, WilKen3 commented on src/main/java/frc/robot/component/Arm.java
> +        ArmPercentOutputUp(State.lTrigger);
☑

2022-02-20 04:34 UTC, WilKen3 commented on src/main/java/frc/robot/component/Arm.java
> +    if(getArmAngle() == -32) {
☑

2022-02-20 04:34 UTC, WilKen3 commented on src/main/java/frc/robot/component/Drive.java
> +        Ddrive.arcadeDrive(Const.neutral,Const.neutral);
☑

2022-02-20 04:34 UTC, WilKen3 commented on src/main/java/frc/robot/mode/ShooterMode.java
> +        if(Math.abs(State.forSpeed) > 0 || Math.abs(State.sideSpeed) > 0){
☑

2022-02-20 06:37 UTC, WilKen3 commented on src/main/java/frc/robot/mode/ShooterMode.java
> +        }
☑

2022-02-20 07:39 UTC, WilKen3 commented
終わりました

2022-02-20 10:32 UTC, Hirose-Yuto commented on src/main/java/frc/robot/State.java
> +    public static double ArmOutputUp, ArmOutputDown;
いろいろ順番がごちゃごちゃなので直したいかな

改行とかもうまく使ってわかりやすくまとめて欲しい

2022-02-20 10:32 UTC, Hirose-Yuto commented on src/main/java/frc/robot/State.java
>      public enum ArmState {
コメントできないのでここで。
30行目なぞのpublic static voidあるけどこれは消し忘れ？

2022-02-20 10:32 UTC, Hirose-Yuto commented on src/main/java/frc/robot/component/Drive.java
> +    dRF.configAllSettings(Const.dRConfig);
どっちもdRF

2022-02-20 10:32 UTC, Hirose-Yuto commented on src/main/java/frc/robot/component/Shooter.java
> +    shooterL.setSelectedSensorPosition(Const.ShooterInitialPosition);
これは何目的？

2022-02-20 10:32 UTC, Hirose-Yuto commented on src/main/java/frc/robot/component/Shooter.java
>    public void neutral(){
ここ、Const.neutral使おう

（てかConstのフィールド名は大文字始まりだからConst.Neutralでは）

2022-02-20 10:32 UTC, Hirose-Yuto commented on src/main/java/frc/robot/mode/ShooterMode.java
> +        }
このチェックは何？

2022-02-20 10:32 UTC, Hirose-Yuto commented on src/main/java/frc/robot/subClass/ShuffleBoard.java
>    }
これは使い方が良くなくて、Stateを介して出力すべき

まあそれ以前にarmとshooterでnull pointer exceptionが出るけど

2022-02-20 10:51 UTC, WilKen3 commented on src/main/java/frc/robot/component/Shooter.java
> +    shooterL.setSelectedSensorPosition(Const.ShooterInitialPosition);
28行目ですか？

2022-02-20 11:09 UTC, WilKen3 commented on src/main/java/frc/robot/State.java
> +    public static double ArmOutputUp, ArmOutputDown;
☑

2022-02-20 11:12 UTC, WilKen3 commented on src/main/java/frc/robot/State.java
>      public enum ArmState {
37行目のstateResetのメソッド用でした

2022-02-20 11:13 UTC, WilKen3 commented on src/main/java/frc/robot/State.java
>      public enum ArmState {
☑

2022-02-20 11:14 UTC, WilKen3 commented on src/main/java/frc/robot/component/Drive.java
> +    dRF.configAllSettings(Const.dRConfig);
☑

2022-02-20 11:18 UTC, WilKen3 commented on src/main/java/frc/robot/component/Shooter.java
>    public void neutral(){
☑

2022-02-20 11:25 UTC, WilKen3 commented on src/main/java/frc/robot/subClass/ShuffleBoard.java
>    }
☑

2022-02-20 11:26 UTC, WilKen3 commented on src/main/java/frc/robot/component/Shooter.java
> +    shooterL.setSelectedSensorPosition(Const.ShooterInitialPosition);
☑ sensorPositionはshooterのPIDを設定したときに足したもの

2022-02-21 06:00 UTC, WilKen3 commented
終わりました

2022-02-21 10:58 UTC, Hirose-Yuto commented on src/main/java/frc/robot/component/Shooter.java
> +    shooterL.setSelectedSensorPosition(Const.ShooterInitialPosition);
何のためにこれを付け足したのかなって
今の操作ではPosition関係なさそうな気がしたから

2022-02-21 11:00 UTC, Hirose-Yuto commented
大体LGTM
あとは実際に動かすだけかな

2022-02-23 10:05 UTC, merged