fix shooter motor
WilKen3/RobotCodeTest1 pull request #8
Opened 2022-02-01 08:16 UTC by WilKen3

2022-02-01 09:23 UTC, Hirose-Yuto commented
あ、マージしていいよ
こちらはその権限がないので自分でしてもらって

2022-02-03 09:31 UTC, Hirose-Yuto commented
マージしていいけどコンフリクトしてるんでその解消よろしく

2022-02-03 10:08 UTC, WilKen3 commented
close #2

2022-02-03 10:10 UTC, Hirose-Yuto requested changes

2022-02-03 10:10 UTC, Hirose-Yuto commented on src/main/java/frc/robot/subClass/Shooter.java
> +    shooterR.set(ControlMode.PercentOutput, Const.ShooterRightOut);
これだと左右のシューターのスピードが揃ってない(はず)

2022-02-07 04:20 UTC, merged